export const COUNTRIES = [
  { name: "Afghanistan", dialing_code: "93", code: "AF" },
  { name: "Albania", dialing_code: "355", code: "AL" },
  { name: "Algeria", dialing_code: "213", code: "DZ" },
  { name: "American Samoa", dialing_code: "1-684", code: "AS" },
  { name: "Andorra", dialing_code: "376", code: "AD" },
  { name: "Angola", dialing_code: "244", code: "AO" },
  { name: "Anguilla", dialing_code: "1-264", code: "AI" },
  { name: "Antarctica", dialing_code: "672", code: "AQ" },
  { name: "Antigua and Barbuda", dialing_code: "1-268", code: "AG" },
  { name: "Argentina", dialing_code: "54", code: "AR" },
  { name: "Armenia", dialing_code: "374", code: "AM" },
  { name: "Aruba", dialing_code: "297", code: "AW" },
  { name: "Australia", dialing_code: "61", code: "AU" },
  { name: "Austria", dialing_code: "43", code: "AT" },
  { name: "Azerbaijan", dialing_code: "994", code: "AZ" },
  { name: "Bahamas", dialing_code: "1-242", code: "BS" },
  { name: "Bahrain", dialing_code: "973", code: "BH" },
  { name: "Bangladesh", dialing_code: "880", code: "BD" },
  { name: "Barbados", dialing_code: "1-246", code: "BB" },
  { name: "Belarus", dialing_code: "375", code: "BY" },
  { name: "Belgium", dialing_code: "32", code: "BE" },
  { name: "Belize", dialing_code: "501", code: "BZ" },
  { name: "Benin", dialing_code: "229", code: "BJ" },
  { name: "Bermuda", dialing_code: "1-441", code: "BM" },
  { name: "Bhutan", dialing_code: "975", code: "BT" },
  { name: "Bolivia", dialing_code: "591", code: "BO" },
  { name: "Bosnia and Herzegovina", dialing_code: "387", code: "BA" },
  { name: "Botswana", dialing_code: "267", code: "BW" },
  { name: "Brazil", dialing_code: "55", code: "BR" },
  { name: "British Indian Ocean Territory", dialing_code: "246", code: "IO" },
  { name: "British Virgin Islands", dialing_code: "1-284", code: "VG" },
  { name: "Brunei", dialing_code: "673", code: "BN" },
  { name: "Bulgaria", dialing_code: "359", code: "BG" },
  { name: "Burkina Faso", dialing_code: "226", code: "BF" },
  { name: "Burundi", dialing_code: "257", code: "BI" },
  { name: "Cambodia", dialing_code: "855", code: "KH" },
  { name: "Cameroon", dialing_code: "237", code: "CM" },
  { name: "Canada", dialing_code: "1", code: "CA" },
  { name: "Cape Verde", dialing_code: "238", code: "CV" },
  { name: "Cayman Islands", dialing_code: "1-345", code: "KY" },
  { name: "Central African Republic", dialing_code: "236", code: "CF" },
  { name: "Chad", dialing_code: "235", code: "TD" },
  { name: "Chile", dialing_code: "56", code: "CL" },
  { name: "China", dialing_code: "86", code: "CN" },
  { name: "Christmas Island", dialing_code: "61", code: "CX" },
  { name: "Cocos Islands", dialing_code: "61", code: "CC" },
  { name: "Colombia", dialing_code: "57", code: "CO" },
  { name: "Comoros", dialing_code: "269", code: "KM" },
  { name: "Cook Islands", dialing_code: "682", code: "CK" },
  { name: "Costa Rica", dialing_code: "506", code: "CR" },
  { name: "Croatia", dialing_code: "385", code: "HR" },
  { name: "Cuba", dialing_code: "53", code: "CU" },
  { name: "Curacao", dialing_code: "599", code: "CW" },
  { name: "Cyprus", dialing_code: "357", code: "CY" },
  { name: "Czech Republic", dialing_code: "420", code: "CZ" },
  { name: "Democratic Republic of the Congo", dialing_code: "243", code: "CD" },
  { name: "Denmark", dialing_code: "45", code: "DK" },
  { name: "Djibouti", dialing_code: "253", code: "DJ" },
  { name: "Dominica", dialing_code: "1-767", code: "DM" },
  {
    name: "Dominican Republic",
    dialing_code: "1-809, 1-829, 1-849",
    code: "DO",
  },
  { name: "East Timor", dialing_code: "670", code: "TL" },
  { name: "Ecuador", dialing_code: "593", code: "EC" },
  { name: "Egypt", dialing_code: "20", code: "EG" },
  { name: "El Salvador", dialing_code: "503", code: "SV" },
  { name: "Equatorial Guinea", dialing_code: "240", code: "GQ" },
  { name: "Eritrea", dialing_code: "291", code: "ER" },
  { name: "Estonia", dialing_code: "372", code: "EE" },
  { name: "Ethiopia", dialing_code: "251", code: "ET" },
  { name: "Falkland Islands", dialing_code: "500", code: "FK" },
  { name: "Faroe Islands", dialing_code: "298", code: "FO" },
  { name: "Fiji", dialing_code: "679", code: "FJ" },
  { name: "Finland", dialing_code: "358", code: "FI" },
  { name: "France", dialing_code: "33", code: "FR" },
  { name: "French Polynesia", dialing_code: "689", code: "PF" },
  { name: "Gabon", dialing_code: "241", code: "GA" },
  { name: "Gambia", dialing_code: "220", code: "GM" },
  { name: "Georgia", dialing_code: "995", code: "GE" },
  { name: "Germany", dialing_code: "49", code: "DE" },
  { name: "Ghana", dialing_code: "233", code: "GH" },
  { name: "Gibraltar", dialing_code: "350", code: "GI" },
  { name: "Greece", dialing_code: "30", code: "GR" },
  { name: "Greenland", dialing_code: "299", code: "GL" },
  { name: "Grenada", dialing_code: "1-473", code: "GD" },
  { name: "Guam", dialing_code: "1-671", code: "GU" },
  { name: "Guatemala", dialing_code: "502", code: "GT" },
  { name: "Guernsey", dialing_code: "44-1481", code: "GG" },
  { name: "Guinea", dialing_code: "224", code: "GN" },
  { name: "Guinea-Bissau", dialing_code: "245", code: "GW" },
  { name: "Guyana", dialing_code: "592", code: "GY" },
  { name: "Haiti", dialing_code: "509", code: "HT" },
  { name: "Honduras", dialing_code: "504", code: "HN" },
  { name: "Hong Kong", dialing_code: "852", code: "HK" },
  { name: "Hungary", dialing_code: "36", code: "HU" },
  { name: "Iceland", dialing_code: "354", code: "IS" },
  { name: "India", dialing_code: "91", code: "IN" },
  { name: "Indonesia", dialing_code: "62", code: "ID" },
  { name: "Iran", dialing_code: "98", code: "IR" },
  { name: "Iraq", dialing_code: "964", code: "IQ" },
  { name: "Ireland", dialing_code: "353", code: "IE" },
  { name: "Isle of Man", dialing_code: "44-1624", code: "IM" },
  { name: "Israel", dialing_code: "972", code: "IL" },
  { name: "Italy", dialing_code: "39", code: "IT" },
  { name: "Ivory Coast", dialing_code: "225", code: "CI" },
  { name: "Jamaica", dialing_code: "1-876", code: "JM" },
  { name: "Japan", dialing_code: "81", code: "JP" },
  { name: "Jersey", dialing_code: "44-1534", code: "JE" },
  { name: "Jordan", dialing_code: "962", code: "JO" },
  { name: "Kazakhstan", dialing_code: "7", code: "KZ" },
  { name: "Kenya", dialing_code: "254", code: "KE" },
  { name: "Kiribati", dialing_code: "686", code: "KI" },
  { name: "Kosovo", dialing_code: "383", code: "XK" },
  { name: "Kuwait", dialing_code: "965", code: "KW" },
  { name: "Kyrgyzstan", dialing_code: "996", code: "KG" },
  { name: "Laos", dialing_code: "856", code: "LA" },
  { name: "Latvia", dialing_code: "371", code: "LV" },
  { name: "Lebanon", dialing_code: "961", code: "LB" },
  { name: "Lesotho", dialing_code: "266", code: "LS" },
  { name: "Liberia", dialing_code: "231", code: "LR" },
  { name: "Libya", dialing_code: "218", code: "LY" },
  { name: "Liechtenstein", dialing_code: "423", code: "LI" },
  { name: "Lithuania", dialing_code: "370", code: "LT" },
  { name: "Luxembourg", dialing_code: "352", code: "LU" },
  { name: "Macao", dialing_code: "853", code: "MO" },
  { name: "Macedonia", dialing_code: "389", code: "MK" },
  { name: "Madagascar", dialing_code: "261", code: "MG" },
  { name: "Malawi", dialing_code: "265", code: "MW" },
  { name: "Malaysia", dialing_code: "60", code: "MY" },
  { name: "Maldives", dialing_code: "960", code: "MV" },
  { name: "Mali", dialing_code: "223", code: "ML" },
  { name: "Malta", dialing_code: "356", code: "MT" },
  { name: "Marshall Islands", dialing_code: "692", code: "MH" },
  { name: "Mauritania", dialing_code: "222", code: "MR" },
  { name: "Mauritius", dialing_code: "230", code: "MU" },
  { name: "Mayotte", dialing_code: "262", code: "YT" },
  { name: "Mexico", dialing_code: "52", code: "MX" },
  { name: "Micronesia", dialing_code: "691", code: "FM" },
  { name: "Moldova", dialing_code: "373", code: "MD" },
  { name: "Monaco", dialing_code: "377", code: "MC" },
  { name: "Mongolia", dialing_code: "976", code: "MN" },
  { name: "Montenegro", dialing_code: "382", code: "ME" },
  { name: "Montserrat", dialing_code: "1-664", code: "MS" },
  { name: "Morocco", dialing_code: "212", code: "MA" },
  { name: "Mozambique", dialing_code: "258", code: "MZ" },
  { name: "Myanmar", dialing_code: "95", code: "MM" },
  { name: "Namibia", dialing_code: "264", code: "NA" },
  { name: "Nauru", dialing_code: "674", code: "NR" },
  { name: "Nepal", dialing_code: "977", code: "NP" },
  { name: "Netherlands", dialing_code: "31", code: "NL" },
  { name: "Netherlands Antilles", dialing_code: "599", code: "AN" },
  { name: "New Caledonia", dialing_code: "687", code: "NC" },
  { name: "New Zealand", dialing_code: "64", code: "NZ" },
  { name: "Nicaragua", dialing_code: "505", code: "NI" },
  { name: "Niger", dialing_code: "227", code: "NE" },
  { name: "Nigeria", dialing_code: "234", code: "NG" },
  { name: "Niue", dialing_code: "683", code: "NU" },
  { name: "North Korea", dialing_code: "850", code: "KP" },
  { name: "Northern Mariana Islands", dialing_code: "1-670", code: "MP" },
  { name: "Norway", dialing_code: "47", code: "NO" },
  { name: "Oman", dialing_code: "968", code: "OM" },
  { name: "Pakistan", dialing_code: "92", code: "PK" },
  { name: "Palau", dialing_code: "680", code: "PW" },
  { name: "Palestine", dialing_code: "970", code: "PS" },
  { name: "Panama", dialing_code: "507", code: "PA" },
  { name: "Papua New Guinea", dialing_code: "675", code: "PG" },
  { name: "Paraguay", dialing_code: "595", code: "PY" },
  { name: "Peru", dialing_code: "51", code: "PE" },
  { name: "Philippines", dialing_code: "63", code: "PH" },
  { name: "Pitcairn", dialing_code: "64", code: "PN" },
  { name: "Poland", dialing_code: "48", code: "PL" },
  { name: "Portugal", dialing_code: "351", code: "PT" },
  { name: "Puerto Rico", dialing_code: "1-787, 1-939", code: "PR" },
  { name: "Qatar", dialing_code: "974", code: "QA" },
  { name: "Republic of the Congo", dialing_code: "242", code: "CG" },
  { name: "Reunion", dialing_code: "262", code: "RE" },
  { name: "Romania", dialing_code: "40", code: "RO" },
  { name: "Russia", dialing_code: "7", code: "RU" },
  { name: "Rwanda", dialing_code: "250", code: "RW" },
  { name: "Saint Barthelemy", dialing_code: "590", code: "BL" },
  { name: "Saint Helena", dialing_code: "290", code: "SH" },
  { name: "Saint Kitts and Nevis", dialing_code: "1-869", code: "KN" },
  { name: "Saint Lucia", dialing_code: "1-758", code: "LC" },
  { name: "Saint Martin", dialing_code: "590", code: "MF" },
  { name: "Saint Pierre and Miquelon", dialing_code: "508", code: "PM" },
  {
    name: "Saint Vincent and the Grenadines",
    dialing_code: "1-784",
    code: "VC",
  },
  { name: "Samoa", dialing_code: "685", code: "WS" },
  { name: "San Marino", dialing_code: "378", code: "SM" },
  { name: "Sao Tome and Principe", dialing_code: "239", code: "ST" },
  { name: "Saudi Arabia", dialing_code: "966", code: "SA" },
  { name: "Senegal", dialing_code: "221", code: "SN" },
  { name: "Serbia", dialing_code: "381", code: "RS" },
  { name: "Seychelles", dialing_code: "248", code: "SC" },
  { name: "Sierra Leone", dialing_code: "232", code: "SL" },
  { name: "Singapore", dialing_code: "65", code: "SG" },
  { name: "Sint Maarten", dialing_code: "1-721", code: "SX" },
  { name: "Slovakia", dialing_code: "421", code: "SK" },
  { name: "Slovenia", dialing_code: "386", code: "SI" },
  { name: "Solomon Islands", dialing_code: "677", code: "SB" },
  { name: "Somalia", dialing_code: "252", code: "SO" },
  { name: "South Africa", dialing_code: "27", code: "ZA" },
  { name: "South Korea", dialing_code: "82", code: "KR" },
  { name: "South Sudan", dialing_code: "211", code: "SS" },
  { name: "Spain", dialing_code: "34", code: "ES" },
  { name: "Sri Lanka", dialing_code: "94", code: "LK" },
  { name: "Sudan", dialing_code: "249", code: "SD" },
  { name: "Suriname", dialing_code: "597", code: "SR" },
  { name: "Svalbard and Jan Mayen", dialing_code: "47", code: "SJ" },
  { name: "Swaziland", dialing_code: "268", code: "SZ" },
  { name: "Sweden", dialing_code: "46", code: "SE" },
  { name: "Switzerland", dialing_code: "41", code: "CH" },
  { name: "Syria", dialing_code: "963", code: "SY" },
  { name: "Taiwan", dialing_code: "886", code: "TW" },
  { name: "Tajikistan", dialing_code: "992", code: "TJ" },
  { name: "Tanzania", dialing_code: "255", code: "TZ" },
  { name: "Thailand", dialing_code: "66", code: "TH" },
  { name: "Togo", dialing_code: "228", code: "TG" },
  { name: "Tokelau", dialing_code: "690", code: "TK" },
  { name: "Tonga", dialing_code: "676", code: "TO" },
  { name: "Trinidad and Tobago", dialing_code: "1-868", code: "TT" },
  { name: "Tunisia", dialing_code: "216", code: "TN" },
  { name: "Turkey", dialing_code: "90", code: "TR" },
  { name: "Turkmenistan", dialing_code: "993", code: "TM" },
  { name: "Turks and Caicos Islands", dialing_code: "1-649", code: "TC" },
  { name: "Tuvalu", dialing_code: "688", code: "TV" },
  { name: "U.S. Virgin Islands", dialing_code: "1-340", code: "VI" },
  { name: "Uganda", dialing_code: "256", code: "UG" },
  { name: "Ukraine", dialing_code: "380", code: "UA" },
  { name: "United Arab Emirates", dialing_code: "971", code: "AE" },
  { name: "United Kingdom", dialing_code: "44", code: "GB" },
  { name: "United States", dialing_code: "1", code: "US" },
  { name: "Uruguay", dialing_code: "598", code: "UY" },
  { name: "Uzbekistan", dialing_code: "998", code: "UZ" },
  { name: "Vanuatu", dialing_code: "678", code: "VU" },
  { name: "Vatican", dialing_code: "379", code: "VA" },
  { name: "Venezuela", dialing_code: "58", code: "VE" },
  { name: "Vietnam", dialing_code: "84", code: "VN" },
  { name: "Wallis and Futuna", dialing_code: "681", code: "WF" },
  { name: "Western Sahara", dialing_code: "212", code: "EH" },
  { name: "Yemen", dialing_code: "967", code: "YE" },
  { name: "Zambia", dialing_code: "260", code: "ZM" },
  { name: "Zimbabwe", dialing_code: "263", code: "ZW" },
];
export const PHONE_COUNTRIES = [
  { name: "Afghanistan |  +93", code: "AF" },
  { name: "Albania |  +355", code: "AL" },
  { name: "Algeria |  +213", code: "DZ" },
  { name: "American Samoa |  +1-684", code: "AS" },
  { name: "Andorra |  +376", code: "AD" },
  { name: "Angola |  +244", code: "AO" },
  { name: "Anguilla |  +1-264", code: "AI" },
  { name: "Antarctica |  +672", code: "AQ" },
  { name: "Antigua and Barbuda |  +1-268", code: "AG" },
  { name: "Argentina |  +54", code: "AR" },
  { name: "Armenia |  +374", code: "AM" },
  { name: "Aruba |  +297", code: "AW" },
  { name: "Australia |  +61", code: "AU" },
  { name: "Austria |  +43", code: "AT" },
  { name: "Azerbaijan |  +994", code: "AZ" },
  { name: "Bahamas |  +1-242", code: "BS" },
  { name: "Bahrain |  +973", code: "BH" },
  { name: "Bangladesh |  +880", code: "BD" },
  { name: "Barbados |  +1-246", code: "BB" },
  { name: "Belarus |  +375", code: "BY" },
  { name: "Belgium |  +32", code: "BE" },
  { name: "Belize |  +501", code: "BZ" },
  { name: "Benin |  +229", code: "BJ" },
  { name: "Bermuda |  +1-441", code: "BM" },
  { name: "Bhutan |  +975", code: "BT" },
  { name: "Bolivia |  +591", code: "BO" },
  { name: "Bosnia and Herzegovina |  +387", code: "BA" },
  { name: "Botswana |  +267", code: "BW" },
  { name: "Brazil |  +55", code: "BR" },
  { name: "British Indian Ocean Territory |  +246", code: "IO" },
  { name: "British Virgin Islands |  +1-284", code: "VG" },
  { name: "Brunei |  +673", code: "BN" },
  { name: "Bulgaria |  +359", code: "BG" },
  { name: "Burkina Faso |  +226", code: "BF" },
  { name: "Burundi |  +257", code: "BI" },
  { name: "Cambodia |  +855", code: "KH" },
  { name: "Cameroon |  +237", code: "CM" },
  { name: "Canada |  +1", code: "CA" },
  { name: "Cape Verde |  +238", code: "CV" },
  { name: "Cayman Islands |  +1-345", code: "KY" },
  { name: "Central African Republic |  +236", code: "CF" },
  { name: "Chad |  +235", code: "TD" },
  { name: "Chile |  +56", code: "CL" },
  { name: "China |  +86", code: "CN" },
  { name: "Christmas Island |  +61", code: "CX" },
  { name: "Cocos Islands |  +61", code: "CC" },
  { name: "Colombia |  +57", code: "CO" },
  { name: "Comoros |  +269", code: "KM" },
  { name: "Cook Islands |  +682", code: "CK" },
  { name: "Costa Rica |  +506", code: "CR" },
  { name: "Croatia |  +385", code: "HR" },
  { name: "Cuba |  +53", code: "CU" },
  { name: "Curacao |  +599", code: "CW" },
  { name: "Cyprus |  +357", code: "CY" },
  { name: "Czech Republic |  +420", code: "CZ" },
  { name: "Democratic Republic of the Congo |  +243", code: "CD" },
  { name: "Denmark |  +45", code: "DK" },
  { name: "Djibouti |  +253", code: "DJ" },
  { name: "Dominica |  +1-767", code: "DM" },
  {
    name: "Dominican Republic",
    dialing_code: "1-809, 1-829, 1-849",
    code: "DO",
  },
  { name: "East Timor |  +670", code: "TL" },
  { name: "Ecuador |  +593", code: "EC" },
  { name: "Egypt |  +20", code: "EG" },
  { name: "El Salvador |  +503", code: "SV" },
  { name: "Equatorial Guinea |  +240", code: "GQ" },
  { name: "Eritrea |  +291", code: "ER" },
  { name: "Estonia |  +372", code: "EE" },
  { name: "Ethiopia |  +251", code: "ET" },
  { name: "Falkland Islands |  +500", code: "FK" },
  { name: "Faroe Islands |  +298", code: "FO" },
  { name: "Fiji |  +679", code: "FJ" },
  { name: "Finland |  +358", code: "FI" },
  { name: "France |  +33", code: "FR" },
  { name: "French Polynesia |  +689", code: "PF" },
  { name: "Gabon |  +241", code: "GA" },
  { name: "Gambia |  +220", code: "GM" },
  { name: "Georgia |  +995", code: "GE" },
  { name: "Germany |  +49", code: "DE" },
  { name: "Ghana |  +233", code: "GH" },
  { name: "Gibraltar |  +350", code: "GI" },
  { name: "Greece |  +30", code: "GR" },
  { name: "Greenland |  +299", code: "GL" },
  { name: "Grenada |  +1-473", code: "GD" },
  { name: "Guam |  +1-671", code: "GU" },
  { name: "Guatemala |  +502", code: "GT" },
  { name: "Guernsey |  +44-1481", code: "GG" },
  { name: "Guinea |  +224", code: "GN" },
  { name: "Guinea-Bissau |  +245", code: "GW" },
  { name: "Guyana |  +592", code: "GY" },
  { name: "Haiti |  +509", code: "HT" },
  { name: "Honduras |  +504", code: "HN" },
  { name: "Hong Kong |  +852", code: "HK" },
  { name: "Hungary |  +36", code: "HU" },
  { name: "Iceland |  +354", code: "IS" },
  { name: "India |  +91", code: "IN" },
  { name: "Indonesia |  +62", code: "ID" },
  { name: "Iran |  +98", code: "IR" },
  { name: "Iraq |  +964", code: "IQ" },
  { name: "Ireland |  +353", code: "IE" },
  { name: "Isle of Man |  +44-1624", code: "IM" },
  { name: "Israel |  +972", code: "IL" },
  { name: "Italy |  +39", code: "IT" },
  { name: "Ivory Coast |  +225", code: "CI" },
  { name: "Jamaica |  +1-876", code: "JM" },
  { name: "Japan |  +81", code: "JP" },
  { name: "Jersey |  +44-1534", code: "JE" },
  { name: "Jordan |  +962", code: "JO" },
  { name: "Kazakhstan |  +7", code: "KZ" },
  { name: "Kenya |  +254", code: "KE" },
  { name: "Kiribati |  +686", code: "KI" },
  { name: "Kosovo |  +383", code: "XK" },
  { name: "Kuwait |  +965", code: "KW" },
  { name: "Kyrgyzstan |  +996", code: "KG" },
  { name: "Laos |  +856", code: "LA" },
  { name: "Latvia |  +371", code: "LV" },
  { name: "Lebanon |  +961", code: "LB" },
  { name: "Lesotho |  +266", code: "LS" },
  { name: "Liberia |  +231", code: "LR" },
  { name: "Libya |  +218", code: "LY" },
  { name: "Liechtenstein |  +423", code: "LI" },
  { name: "Lithuania |  +370", code: "LT" },
  { name: "Luxembourg |  +352", code: "LU" },
  { name: "Macao |  +853", code: "MO" },
  { name: "Macedonia |  +389", code: "MK" },
  { name: "Madagascar |  +261", code: "MG" },
  { name: "Malawi |  +265", code: "MW" },
  { name: "Malaysia |  +60", code: "MY" },
  { name: "Maldives |  +960", code: "MV" },
  { name: "Mali |  +223", code: "ML" },
  { name: "Malta |  +356", code: "MT" },
  { name: "Marshall Islands |  +692", code: "MH" },
  { name: "Mauritania |  +222", code: "MR" },
  { name: "Mauritius |  +230", code: "MU" },
  { name: "Mayotte |  +262", code: "YT" },
  { name: "Mexico |  +52", code: "MX" },
  { name: "Micronesia |  +691", code: "FM" },
  { name: "Moldova |  +373", code: "MD" },
  { name: "Monaco |  +377", code: "MC" },
  { name: "Mongolia |  +976", code: "MN" },
  { name: "Montenegro |  +382", code: "ME" },
  { name: "Montserrat |  +1-664", code: "MS" },
  { name: "Morocco |  +212", code: "MA" },
  { name: "Mozambique |  +258", code: "MZ" },
  { name: "Myanmar |  +95", code: "MM" },
  { name: "Namibia |  +264", code: "NA" },
  { name: "Nauru |  +674", code: "NR" },
  { name: "Nepal |  +977", code: "NP" },
  { name: "Netherlands |  +31", code: "NL" },
  { name: "Netherlands Antilles |  +599", code: "AN" },
  { name: "New Caledonia |  +687", code: "NC" },
  { name: "New Zealand |  +64", code: "NZ" },
  { name: "Nicaragua |  +505", code: "NI" },
  { name: "Niger |  +227", code: "NE" },
  { name: "Nigeria |  +234", code: "NG" },
  { name: "Niue |  +683", code: "NU" },
  { name: "North Korea |  +850", code: "KP" },
  { name: "Northern Mariana Islands |  +1-670", code: "MP" },
  { name: "Norway |  +47", code: "NO" },
  { name: "Oman |  +968", code: "OM" },
  { name: "Pakistan |  +92", code: "PK" },
  { name: "Palau |  +680", code: "PW" },
  { name: "Palestine |  +970", code: "PS" },
  { name: "Panama |  +507", code: "PA" },
  { name: "Papua New Guinea |  +675", code: "PG" },
  { name: "Paraguay |  +595", code: "PY" },
  { name: "Peru |  +51", code: "PE" },
  { name: "Philippines |  +63", code: "PH" },
  { name: "Pitcairn |  +64", code: "PN" },
  { name: "Poland |  +48", code: "PL" },
  { name: "Portugal |  +351", code: "PT" },
  { name: "Puerto Rico |  +1-787, 1-939", code: "PR" },
  { name: "Qatar |  +974", code: "QA" },
  { name: "Republic of the Congo |  +242", code: "CG" },
  { name: "Reunion |  +262", code: "RE" },
  { name: "Romania |  +40", code: "RO" },
  { name: "Russia |  +7", code: "RU" },
  { name: "Rwanda |  +250", code: "RW" },
  { name: "Saint Barthelemy |  +590", code: "BL" },
  { name: "Saint Helena |  +290", code: "SH" },
  { name: "Saint Kitts and Nevis |  +1-869", code: "KN" },
  { name: "Saint Lucia |  +1-758", code: "LC" },
  { name: "Saint Martin |  +590", code: "MF" },
  { name: "Saint Pierre and Miquelon |  +508", code: "PM" },
  {
    name: "Saint Vincent and the Grenadines",
    dialing_code: "1-784",
    code: "VC",
  },
  { name: "Samoa |  +685", code: "WS" },
  { name: "San Marino |  +378", code: "SM" },
  { name: "Sao Tome and Principe |  +239", code: "ST" },
  { name: "Saudi Arabia |  +966", code: "SA" },
  { name: "Senegal |  +221", code: "SN" },
  { name: "Serbia |  +381", code: "RS" },
  { name: "Seychelles |  +248", code: "SC" },
  { name: "Sierra Leone |  +232", code: "SL" },
  { name: "Singapore |  +65", code: "SG" },
  { name: "Sint Maarten |  +1-721", code: "SX" },
  { name: "Slovakia |  +421", code: "SK" },
  { name: "Slovenia |  +386", code: "SI" },
  { name: "Solomon Islands |  +677", code: "SB" },
  { name: "Somalia |  +252", code: "SO" },
  { name: "South Africa |  +27", code: "ZA" },
  { name: "South Korea |  +82", code: "KR" },
  { name: "South Sudan |  +211", code: "SS" },
  { name: "Spain |  +34", code: "ES" },
  { name: "Sri Lanka |  +94", code: "LK" },
  { name: "Sudan |  +249", code: "SD" },
  { name: "Suriname |  +597", code: "SR" },
  { name: "Svalbard and Jan Mayen |  +47", code: "SJ" },
  { name: "Swaziland |  +268", code: "SZ" },
  { name: "Sweden |  +46", code: "SE" },
  { name: "Switzerland |  +41", code: "CH" },
  { name: "Syria |  +963", code: "SY" },
  { name: "Taiwan |  +886", code: "TW" },
  { name: "Tajikistan |  +992", code: "TJ" },
  { name: "Tanzania |  +255", code: "TZ" },
  { name: "Thailand |  +66", code: "TH" },
  { name: "Togo |  +228", code: "TG" },
  { name: "Tokelau |  +690", code: "TK" },
  { name: "Tonga |  +676", code: "TO" },
  { name: "Trinidad and Tobago |  +1-868", code: "TT" },
  { name: "Tunisia |  +216", code: "TN" },
  { name: "Turkey |  +90", code: "TR" },
  { name: "Turkmenistan |  +993", code: "TM" },
  { name: "Turks and Caicos Islands |  +1-649", code: "TC" },
  { name: "Tuvalu |  +688", code: "TV" },
  { name: "U.S. Virgin Islands |  +1-340", code: "VI" },
  { name: "Uganda |  +256", code: "UG" },
  { name: "Ukraine |  +380", code: "UA" },
  { name: "United Arab Emirates |  +971", code: "AE" },
  { name: "United Kingdom |  +44", code: "GB" },
  { name: "United States |  +1", code: "US" },
  { name: "Uruguay |  +598", code: "UY" },
  { name: "Uzbekistan |  +998", code: "UZ" },
  { name: "Vanuatu |  +678", code: "VU" },
  { name: "Vatican |  +379", code: "VA" },
  { name: "Venezuela |  +58", code: "VE" },
  { name: "Vietnam |  +84", code: "VN" },
  { name: "Wallis and Futuna |  +681", code: "WF" },
  { name: "Western Sahara |  +212", code: "EH" },
  { name: "Yemen |  +967", code: "YE" },
  { name: "Zambia |  +260", code: "ZM" },
  { name: "Zimbabwe |  +263", code: "ZW" },
];
